# navigation_classes.py

NAVIGATION_CLASSES = {
    'person': 0,
    'bicycle': 1,
    'car': 2,
    'motorcycle': 3,
    'bus': 5,
    'train': 6,
    'truck': 7,
    'traffic light': 9,
    'fire hydrant': 10,
    'stop sign': 11,
    'parking meter': 12,
    'bench': 13,
    'bird': 14,
    'cat': 15,
    'dog': 16,
    'backpack': 24,
    'umbrella': 25,
    'handbag': 26,
    'tie': 27,
    'suitcase': 28,
    'frisbee': 29,
    'skis': 30,
    'snowboard': 31,
    'sports ball': 32,
    'kite': 33,
    'baseball bat': 34,
    'baseball glove': 35,
    'skateboard': 36,
    'surfboard': 37,
    'tennis racket': 38,
    'bottle': 39,
    'wine glass': 40,
    'cup': 41,
    'fork': 42,
    'knife': 43,
    'spoon': 44,
    'bowl': 45,
    'banana': 46,
    'apple': 47,
    'sandwich': 48,
    'orange': 49,
    'broccoli': 50,
    'carrot': 51,
    'hot dog': 52,
    'pizza': 53,
    'donut': 54,
    'cake': 55,
    'chair': 56,
    'couch': 57,
    'potted plant': 58,
    'bed': 59,
    'dining table': 60,
    'toilet': 61,
    'tv': 62,
    'laptop': 63,
    'mouse': 64,
    'remote': 65,
    'keyboard': 66,
    'cell phone': 67,
    'microwave': 68,
    'oven': 69,
    'toaster': 70,
    'sink': 71,
    'refrigerator': 72,
    'book': 73,
    'clock': 74,
    'vase': 75,
    'scissors': 76,
    'teddy bear': 77,
    'hair drier': 78,
    'toothbrush': 79
}

# Priority levels for narration (1 = highest priority)
PRIORITY_MAP = {
    # High priority - safety critical
    'person': 1,
    'car': 1,
    'bus': 1,
    'truck': 1,
    'train': 1,
    'motorcycle': 1,
    'bicycle': 1,
    'traffic light': 1,
    'stop sign': 1,
    'dog': 1,
    'cat': 1,
    
    # Medium priority - obstacles
    'fire hydrant': 2,
    'bench': 2,
    'chair': 2,
    'couch': 2,
    'dining table': 2,
    'potted plant': 2,
    'suitcase': 2,
    'backpack': 2,
    
    # Lower priority - objects of interest
    'tv': 3,
    'laptop': 3,
    'cell phone': 3,
    'book': 3,
    'clock': 3,
    'bottle': 3,
    'cup': 3,
}